---
version: '3.8'

services:
  weather-exporter:
    build: .
    environment:
      - LATITUDE
      - LONGITUDE
    ports:
      - 8080:8080

  prometheus:
    image: docker.io/prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
